//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseasedetector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diseasedetector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Camera {
            get {
                object obj = ResourceManager.GetObject("Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Correct {
            get {
                object obj = ResourceManager.GetObject("Correct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap female {
            get {
                object obj = ResourceManager.GetObject("female", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Intro {
            get {
                object obj = ResourceManager.GetObject("Intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap male {
            get {
                object obj = ResourceManager.GetObject("male", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Expression_Encoder {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Expression_Encoder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Expression_Encoder_Api2 {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Expression_Encoder_Api2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///        &quot;EncoderApi2&quot;
        ///    &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;M:Microsoft.Expression.Encoder.Profiles.LocalProfiles.EnumerateAudioCodecs(System.Collections.ObjectModel.ObservableCollection`1{Microsoft.Expression.Encoder.Profiles.AudioProfile})&quot;&gt;
        ///      &lt;summary&gt;
        ///Enumerate the collection of audio profiles that are installed on the system.
        ///&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;P:Microsoft.Expression.Encoder.Profiles.LocalProfiles.AudioProfiles&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Expression_Encoder_Api21 {
            get {
                return ResourceManager.GetString("Microsoft_Expression_Encoder_Api21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version =&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;msbuildToolsets&quot; type=&quot;Microsoft.Build.BuildEngine.ToolsetConfigurationSection, Microsoft.Build.Engine, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v2.0.50727&quot; safemode=&quot;true&quot;/&gt;
        ///    &lt;requiredRuntime version=&quot;v2.0.50727&quot; safemode=&quot;true&quot;/&gt;
        ///  &lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Expression_Encoder_dll {
            get {
                return ResourceManager.GetString("Microsoft_Expression_Encoder_dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Expression_Encoder_Types {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Expression_Encoder_Types", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;Microsoft.Expression.Encoder.Types&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:Microsoft.Expression.Encoder.Profiles.AudioCodec&quot;&gt;
        ///      &lt;summary&gt;
        ///            Contains the audio codecs that Expression Encoder supports as output types.
        ///            &lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;F:Microsoft.Expression.Encoder.Profiles.AudioCodec.Unknown&quot;&gt;
        ///      &lt;summary&gt;
        ///            The audio codec is unknown.
        ///            &lt;/summary&gt;
        ///    &lt;/me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Expression_Encoder_Types1 {
            get {
                return ResourceManager.GetString("Microsoft_Expression_Encoder_Types1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Expression_Encoder_Utilities {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Expression_Encoder_Utilities", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///        &quot;EncoderUtil&quot;
        ///    &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;M:Microsoft.Expression.Encoder.UnableToCreateThumbnailException.#ctor(System.String,System.Exception)&quot;&gt;
        ///      &lt;summary&gt;
        ///Initializes a new instance of the UnableToCreateThumbnailException from an exception.
        ///&lt;/summary&gt;
        ///      &lt;param name=&quot;message&quot;&gt;The error message that explains the reason for the exception.&lt;/param&gt;
        ///      &lt;param name=&quot;innerException&quot;&gt;The exception that is the cause of the cur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Expression_Encoder_Utilities1 {
            get {
                return ResourceManager.GetString("Microsoft_Expression_Encoder_Utilities1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;Microsoft.Expression.Encoder&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:Microsoft.Expression.Encoder.EncodeThumbnailProgressEventArgs&quot;&gt;
        ///      &lt;summary&gt;
        ///            Contains the arguments of the encode progress event.
        ///            &lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:Microsoft.Expression.Encoder.EncodeThumbnailProgressEventArgs.#ctor(System.Int32,System.Int32)&quot;&gt;
        ///      &lt;summary&gt;
        ///            Initializes a new instance of the Encod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Expression_Encoder1 {
            get {
                return ResourceManager.GetString("Microsoft_Expression_Encoder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Record {
            get {
                object obj = ResourceManager.GetObject("Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Symptom1 {
            get {
                object obj = ResourceManager.GetObject("Symptom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wrong {
            get {
                object obj = ResourceManager.GetObject("Wrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
